name: deploy gh-pages
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and deploy gh-pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set-up Node
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: npm install & build
      run: |
        npm install
        npm run build
        cp dist/index.html dist/404.html
    # 透過 peaceiris/actions-gh-pages@v3 套件，協助佈版至 gh-pages
    # https://github.com/marketplace/actions/github-pages-action
    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: ./dist
